FROM node:20-alpine
WORKDIR /app

RUN npm install -g bun

COPY package.json bun.lock ./
COPY apps/admin/package.json ./apps/admin/
COPY packages/shared ./packages/shared

RUN bun install

COPY apps/admin ./apps/admin

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NODE_ENV=production

WORKDIR /app/apps/admin
RUN npm run build

EXPOSE 3002
ENV PORT=3002
ENV HOSTNAME="0.0.0.0"
CMD ["npm", "start"]
