FROM oven/bun:1
WORKDIR /app

COPY package.json bun.lock ./
COPY apps/api/package.json ./apps/api/
COPY packages/shared ./packages/shared

RUN bun install

COPY apps/api ./apps/api

WORKDIR /app/apps/api
RUN bun run build

ENV NODE_ENV=production
RUN mkdir -p /app/uploads

EXPOSE 3001
CMD ["bun", "run", "start:prod"]
